name: Integration test
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  integration-test:
    runs-on: ubuntu-latest
    name: test
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - uses: docker/build-push-action@v3
      with:
        tags: feed-cli-test:latest
        push: false
        context: ./integration-test/local-rss/.
    - uses: addnab/docker-run-action@v3
      with:
        image: feed-cli-test:latest
        run: integration-test/local-rss/test.sh
