name: Integration test
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Build the RSS image
      run: docker build . --file integration-test/local-rss/Dockerfile --tag 0.1.0:v0.1.0
    - name: Run RSS Server
      run: docker run feed-cli-test:0.1.0
    - name: Run Test
      run: sh integration-test/local-rss/test.sh
