name: Integration test
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  integration-test:
    runs-on: ubuntu-latest
    name: test
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Build the test image
      run: docker build --file ./integration-test/local-rss/Dockerfile --tag feed-cli-test:0.1.0 ./integration-test/local-rss/.
    - name: Run Test
      run: sh integration-test/local-rss/test.sh
